# Generated by Django 4.1.3 on 2023-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_commentbyclassroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='date',
            field=models.DateField(auto_created=True, default=None),
        ),
    ]
