# Generated by Django 4.1.3 on 2023-03-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_classroom_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
